sonar.projectKey=ecommerce-app
sonar.projectName=Ecommerce App
sonar.sources=frontend/src,product-service/src,order-service/src,user-service/src,payment-service/src
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js,**/target/**
