apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: ecommerce
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecommerce-db-secrets
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: ecommerce-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_URI
    remoteRef:
      key: ecommerce/db-secrets
      property: POSTGRES_URI
  - secretKey: MONGODB_URI
    remoteRef:
      key: ecommerce/db-secrets
      property: MONGODB_URI
  - secretKey: JWT_SECRET
    remoteRef:
      key: ecommerce/db-secrets
      property: JWT_SECRET
