apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - mongodb.yaml
  - user-service.yaml
  - product-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - frontend.yaml
  - ingress.yaml
