apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_URI: "postgresql://ecomuser:ecompassword@postgres-service:5432/ecomdb"
  JWT_SECRET: "ecommerce-secret-key-change-in-production"
